### ISSUE TITLE
Sleep doesn't fully work

### ISSUE THREAD

**Issue by jamieernest** [jamieernest/Dell-Inspiron-7501-Hackintosh#1]
Refer to [Readme.md](https://github.com/jamieernest/Dell-Inspiron-7501-Hackintosh/)

**Comment by IamBigv** [comment]
[DELL INSPIRON 7501.zip](https://github.com/jamieernest/Dell-Inspiron-7501-Hackintosh/files/5656575/DELL.INSPIRON.7501.zip)

**Comment by jamieernest** [comment]
> [DELL INSPIRON 7501.zip](https://github.com/jamieernest/Dell-Inspiron-7501-Hackintosh/files/5656575/DELL.INSPIRON.7501.zip)
你好，你可以跟我說你的EFI跟我的有什麼分別？還有你的1650ti在macOS關掉了嗎？可以正常地睡眠嗎？
(for english readers: Hello, can you tell me what is the difference of the EFI and mine? Is your 1650Ti turned off in macOS? Can it sleep normally?)

**Comment by jamieernest** [comment]
謝謝你！！加了 SSDT-GPRW 後睡眠就立即成功了！謝謝！
