### ISSUE TITLE
nvme fatal error

### ISSUE THREAD

**Issue by UniversessH** [jamieernest/Dell-Inspiron-7501-Hackintosh#10]
Hi，there
I‘v just used your config,but i‘v seen this fatal problem
My SSD is WD sn730 
can you help me to solve this problem? ![image](https://user-images.githubusercontent.com/71715910/134315208-07c1911d-8064-4a06-b710-07ef0f8df725.jpeg)
![image](https://user-images.githubusercontent.com/71715910/134315232-f48075f3-d850-4f84-b3bb-0d784e4e5bef.jpeg)

**Comment by jamieernest** [comment]
Can I have your EFI?

**Comment by UniversessH** [comment]
> Can I have your EFI?

Hi,there
I‘ve solved this problem,it seems that my main SSD has some problems with OC (I use another SSD for installing MacOS), OC can only work when I turned off my main SSD in BIOS,now I‘ve entered the system.

**Comment by 87357163** [comment]
UniversessH     Can I have your  OC EFI？ My 7501 also wants to install Mac OS，thank you。
E-mail：87357163@qq.com
