### ISSUE TITLE
OC 升级 0.7.6

### ISSUE THREAD

**Issue by ghost** [jamieernest/Dell-Inspiron-7501-Hackintosh#11]
Hi 朋友，我借鉴了你的EFI配置文件，但是USB2.0无法使用，摄像头无法使用 。我重新定制了USB。目前工作正常。我把OC升级到了0.7.6.在升级核心显卡WhateverGreen.kext驱动后，笔记本屏幕无输出，系统正常运行。我尝试了修改ID，仍无法解决。附上EFI链接：www.aliyundrive.com/s/32hwfExQf71  。如有时间，请帮忙指导，感谢分享。

**Comment by jamieernest** [comment]
你好！我會這個星期上載一個新版本，希望會解決到你的問題！

**Comment by jamieernest** [comment]
Issue closed, account deleted, no way of getting user feedback.
