### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by alexstuccer** [jamieernest/Dell-Inspiron-7501-Hackintosh#2]
Hi there,
first of all, thanks for your guide. I successfully installed catalina on my inspiron 7501. I found these issues:
1) I tryed to install big sur with the same EFI, but I can't reach system installer, the screen stops as apple appears.
2) My bluetooth (dw1560) is not working properly. It works, but no airdrop, and sometimes it just falls. Can't use sidecar with my ipad pro either.

I hope you find a solution for mycrophone. Once again thanks!

**Comment by jamieernest** [comment]
Hi @alexstuccer, thanks for reaching out to me, for problem 2 can you check if ExtendBTFeatureFlags is set to true in your config.plist? I think I turned it off for the intel wifi. For problem 1 can you tell me how you are trying to install Big Sur?

**Comment by jamieernest** [comment]
Can you also test my new release?

**Comment by alexstuccer** [comment]
Thanks for your answer. I used your previous release I think (0.6.3 opencore). As I can I'll test your 0.6.4 release. ExtendBTFeatureFlags was already set to true. It failed several times when I tryed to connect my mouse (logitech m590). It showed 3 mouses instead of 1. At the end it connected, and worked enough well, just sometimes it was a bit laggish. I tryed to connect my ipad, and after some tryes it connected. But when I try to start sidecar it says waiting time for device expired (at least this is my translation, might be a bit different in english). Also, airdrop works just in receiving.
About Big Sur, I skipped the preparation of pendrive, because I already had a vanilla pendrive prepared with clover, I just changed efi folder. I did the same with catalina and it booted up. With Big Sur it just hangs on when there appears the apple.

**Comment by jamieernest** [comment]
This repo is built on OpenCore and I don't think Clover can even boot big sur... maybe you can try using opencore?

**Comment by jamieernest** [comment]
Did you try updating from Catalina to Big Sur via the Software update panel in system prefrences?

**Comment by alexstuccer** [comment]
Sincerely I thought about it, but I didn't dare ;D

**Comment by jamieernest** [comment]
Thats what worked for me... It took a while though... Give it a try

**Comment by jamieernest** [comment]
Regarding the microphone I tried all layouts that are compatible already and none of them have mic support. The trackpad doesnt work because you have both TPDX and GPI0 at the same time and you didnt patch _OSI to OSI for GPI0 (which may likely break windows booting). Browser crashing would probably have something to do with the igpu framebuffer patching, I'm not really sure but for the bluetooth you can try adding brcmfx-driver=2 to your boot args and see if it changes anything. When you used my repo did you use OC Snapshot in Propertree to add the kexts into the config.plist? I didnt add them in the first place because I didnt want to confuse intel wifi users. For intel wifi (original card) the last time I tried it doesnt support WPA Enterprise (which was a deal breaker) but I think they support it now. Handoff and Continuity are the only supported features in bluetooth.

**Comment by alexstuccer** [comment]
Hi again, and thanks for reply. Forget my previous config.plist, is trash. Tonight I spent hours to try to understand audio, and finally I came to your conclusions.
I am happy to say that with your new release I was able to install big sur. 
About snapshot, yes I did. The added kexts are in config.plist now. I'll try that boot arg. 
Thanks again for your project and support.

**Comment by jamieernest** [comment]
No problem!

**Comment by alexstuccer** [comment]
I tryed checking boot args, and brcmfx-driver=2 was already there. So I tryed to delete it, and now sidecar almost works (sometimes can't connect, or loses signal, but normally it works). Airdrop the same. Overall a better experience. I'll try brcmfx-driver=0 and brcmfx-driver=1 maybe, but I have to check what it would mean.
anyway, about audio, I found this about and asus laptop:
https://www.reddit.com/r/hackintosh/comments/irwbz4/internal_microphone_not_working_on_asus_laptop/
let me know if is useful or not. They didn't solve the problem, but someone said he had similar issue and solved it generating a SSDT-HPET, which is not actually present in ACPI folder.

**Comment by jamieernest** [comment]
I generated a SSDT-HPET and it didnt enable the internal microphone but I'm not sure if it affected the jack microphone because I currently don't have anything to test it with.

**Comment by alexstuccer** [comment]
I tested the jack with every single layout for our audio codec, it doesn't work.

**Comment by jamieernest** [comment]
I did that too, did you try to generate a SSDT-HPET and use the patches?

**Comment by jamieernest** [comment]
I just tested jack mic with HPET with patches. It didn't work. I also tried Sidecar and it works perfectly.

**Comment by jamieernest** [comment]
Issue closed, inactive and fixed in my laptop.
