### ISSUE TITLE
EFI

### ISSUE THREAD

**Issue by justice4no1** [jamieernest/Dell-Inspiron-7501-Hackintosh#4]
The Zip does not have the EFI folder that you said to replace,

**Comment by justice4no1** [comment]
No matter what way I try and get the EFI to work it will Kernel panic with Big Sur 11.2.2 - I've tried on try both a Mac and PC to get this working :( Would love some input into what is going wrong, I have confirmed that my Wifi Card is the AX201 and I'm using the right kext and updated the config.plist with proper and added the correct changes via gensmb, Any ideas what could be going wrong.

**Comment by justice4no1** [comment]
Getting a Bootstrap error, I the only difference is that I have an SK Hynix PC711 NVME 1Tb

**Comment by justice4no1** [comment]
resolved the issue changed the NVME Drive with an old San Disk from my last Dell, Big Sur is installing with intel kext right now

**Comment by jamieernest** [comment]
SK Hynix PC711 is known to not work in macOS.
