### ISSUE TITLE
Opencore Update [0.7]

### ISSUE THREAD

**Issue by 6im0n** [jamieernest/Dell-Inspiron-7501-Hackintosh#9]
Is it possible to upgrade to open core 0.7.2 without problems?

**Comment by jamieernest** [comment]
Yes, but I'm going to release an update for 0.7.2 (major changes to config)
so please be patient :)

>

**Comment by ShiinaKaze** [comment]
hi，could you give me some advice about the kernel panic AppleUsbHostController. OpenCore 0.7.3,xhciportlimit, it doesn't work for macOS 11.3+.

**Comment by ShiinaKaze** [comment]
![image](https://user-images.githubusercontent.com/89641145/133915969-9e639b22-c004-4822-a39e-8591ab4168e9.jpeg)

**Comment by jamieernest** [comment]
I haven’t tried MacOS 11.3 yet, but afaik as long as you have UsbMap.kext
(which is included in the repo already) and disable XhciPortLimit in
config.plist it should boot. Check this
https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#reboot-on-appleusbhostport-createdevice-failed-to-create-device-on-macos-11-3
-- 
*Regards*
*Sent from Jamie Kong*

**Comment by ShiinaKaze** [comment]
> I haven’t tried MacOS 11.3 yet, but afaik as long as you have UsbMap.kext
> (which is included in the repo already) and disable XhciPortLimit in
> config.plist it should boot. Check this
> https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#reboot-on-appleusbhostport-createdevice-failed-to-create-device-on-macos-11-3
> 

thanks，bro,but I have tried to solve this problem with the way that you tell me. but it also doesn't work. DELL 7501.

**Comment by jamieernest** [comment]
Can I have the log file?

**Comment by ShiinaKaze** [comment]
sure,wait a moment?> Can I have the log file?

**Comment by ShiinaKaze** [comment]
sorry, I need debug version to collect logs. I can give you my EFI fil
[EFI.zip](https://github.com/jamieernest/Dell-Inspiron-7501-Hackintosh/files/7192034/EFI.zip)
e.

**Comment by jamieernest** [comment]
You don't have USBMap.kext in your efi. Please get it from the kext folder in this repo

**Comment by ShiinaKaze** [comment]
thank you so much, but it stuck at here ![image](https://user-images.githubusercontent.com/89641145/133928600-d2f5df22-0981-482e-8743-b30efee49029.jpeg)![image](https://user-images.githubusercontent.com/89641145/133928620-28569395-6af3-4891-a5e6-d0337f38d176.jpeg)> You don't have USBMap.kext in your efi. Please get it from the kext folder in this repo

**Comment by jamieernest** [comment]
>
> Try set SetupVirtualMap to false
>
-- 
*Regards*
*Sent from Jamie Kong*

**Comment by ShiinaKaze** [comment]
> >
> > Try set SetupVirtualMap to false
> >
> -- 
> *Regards*
> *Sent from Jamie Kong*
> 

![image](https://user-images.githubusercontent.com/89641145/133933112-14c5902b-57ac-45d3-bfe0-8e72cb90e51b.jpeg)
something wrong.

**Comment by ShiinaKaze** [comment]
> > >
> > > Try set SetupVirtualMap to false
> > >
> > -- 
> > *Regards*
> > *Sent from Jamie Kong*
> > 
> 
> ![image](https://user-images.githubusercontent.com/89641145/133933112-14c5902b-57ac-45d3-bfe0-8e72cb90e51b.jpeg)
> ![image](https://user-images.githubusercontent.com/89641145/133933263-9194fda7-7a4d-4c6c-b346-8fa0f904d689.jpeg)
I think stuck at here because of USB.

**Comment by ShiinaKaze** [comment]
Thanks, I have solved the problem. I trying to fix backlight and usb 2.0.

**Comment by jamieernest** [comment]
Glad to hear it!
-- 
*Regards*
*Sent from Jamie Kong*

**Comment by ShiinaKaze** [comment]
USBToolBox project can solve AppleUsbhoster kernel panic.

**Comment by pluie1998** [comment]
> 谢谢，我已经解决了这个问题。我试图修复背光和 USB 2.0。

可否把你的EFI分享与我呢。

**Comment by pluie1998** [comment]
> > 谢谢，我已经解决了这个问题。我改造0和USB 2.。
> 
> 可否把你的EFI分享与我呢。

My email address is pluie1998@outlook.com
Thanks

**Comment by ShiinaKaze** [comment]
I think you better to close this issue.

**Comment by jamieernest** [comment]
Yeah
